
import type { Metadata } from "next";
import {Caveat,Zilla_Slab,Space_Grotesk} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import { navItems } from "./mockData";
import ThemeProvider from "./wrappers/themeProvider";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import AuthProvider from "./wrappers/auth-provider";



const space = Space_Grotesk({ subsets: ["latin"],weight:["500"] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(); // ✅ Get session server-side

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", space.className)}
    
    >
      <body className="min-h-full flex flex-col">
      <AuthProvider session={session}>
      <ThemeProvider>
        <Navbar naItems={navItems}/>
<section className=" px-14 py-10">
{children}

</section>
        </ThemeProvider>
      </AuthProvider>
     
       
     </body>
    </html>
  );
}
